server:
  port: 8888

spring:
  datasource:
    url: jdbc:mysql://123.56.155.237:3306/exercise-spring?useSSL=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver